#!/bin/sh

java -jar ../../../deploy/lib/jetty-runner.jar --port 8080 \
    --lib ../../mmt-web/trunk/lib \
    --jar lib/mmt/mmt-api.jar \
    --lib ../../../deploy/lib/scala \
    lib/mmt/mmt-web.war 2>&1 > jetty.log
