#!/usr/bin/env bash
#
# DESCRIPTION: build and deploy MMT, using sbt

set -e

# Isabelle Scala/Java components
isabelle scala_build

# MMT build
cd "$ISABELLE_MMT_ROOT/src"
sbt mmt/deploy "$@"

# strip material already present in Isabelle classpath
cd "$ISABELLE_MMT_ROOT/deploy"
rm -rf tmp
mkdir tmp
cd tmp
isabelle_jdk jar xf ../mmt.jar
rm -r isabelle org/jline org/tukaani scala
isabelle_jdk jar cf ../mmt.jar .
cd ..
rm -rf tmp
