#!/usr/bin/env bash
#
# DESCRIPTION: build and deploy MMT, using sbt

set -e

# Isabelle Scala/Java components
isabelle_admin_build jars

# MMT build
cd "$ISABELLE_MMT_ROOT/src"
sbt mmt/deploy "$@"

# strip material already present in Isabelle classpath
cd "$ISABELLE_MMT_ROOT/deploy"
rm -rf tmp
mkdir tmp
cd tmp
jar xf ../mmt.jar
rm -r isabelle org/jline org/tukaani scala
jar cf ../mmt.jar .
cd ..
rm -rf tmp
