// Generated by CoffeeScript 1.10.0
(function() {
  window.Treeview = (function() {
    function Treeview(searcher) {
      $(".treeitem").on("contextmenu", function() {
        var callback, i, search_list;
        alert('Adding dummy search list...');
        search_list = (function() {
          var j, results;
          results = [];
          for (i = j = 1; j <= 10000; i = ++j) {
            results.push({
              symbol: "A" + i + "?B" + (2 * i) + "?C" + (3 * i),
              type: "int" + i + "->real" + i
            });
          }
          return results;
        })();
        callback = function(symbol) {
          return alert(symbol + " is selected");
        };
        searcher.create(search_list, callback);
        return false;
      });
    }

    return Treeview;

  })();

}).call(this);

//# sourceMappingURL=treeview.js.map
