#!/bin/bash

pushd .
cd ../../mmt-web/trunk/ && ant
popd

java -jar ../../../deploy/lib/jetty-runner.jar --port 8080 \
    --lib ../../mmt-web/trunk/lib \
    --jar lib/mmt/mmt-api.jar \
    --lib ../../../deploy/lib/scala \
    ../../mmt-web/trunk/build/mmt-web.war # 2>&1 > jetty.log
