#!/bin/sh

if [ -n "$1" ]; then
    if [ "$1" = "c" ]; then
        ant clean
fi

if [ ! -f build/mmt-tptp.jar ]; then
    ant jar
    if [ $? -ne 0 ]; then
        exit 1
    fi
fi

scala -cp build/mmt-tptp.jar:lib/mmt/mmt-api.jar:lib/antlr-3.2.jar:lib/antlr-runtime-3.2.jar:lib/tptp-parser.jar info.kwarc.mmt.api.frontend.Run file run.mmt
