#!/bin/sh

if [ -n "$1" ]; then
    if [ "$1" = "clean" ]; then
        ant clean
    fi
fi

if [ ! -f build/mmt-tptp.jar ]; then
    ant jar
fi

scala -cp build/mmt-tptp.jar:lib/mmt/mmt-api.jar:lib/antlr-3.2.jar:lib/antlr-runtime-3.2.jar:lib/tptp-parser.jar info.kwarc.mmt.api.frontend.Run file run.mmt
