package info.kwarc.mmt.api

/** describes the origin of a generated knowledge item */
abstract class Origin
/** an original declaration */
case object Original extends Origin
/** obtained by elaborating a structure */
case class FromStructure(structure: GlobalName) extends Origin
/** obtained by taking the closure under inclusions
 *  An Include yields further Include element due to transitivity.
 *  A DefLinkAssignment yields further DefLinkAssignment elements by adding those for the theories included into the domain.
 */
case object IncludeClosure extends Origin
/** include generated from meta-theory relation */
case object MetaInclude extends Origin
/** obtained by replacing document parts with references */
case object DocumentSkeleton extends Origin
/** generated by some agent */
case class GeneratedBy(by: AnyRef) extends Origin
/** materialized module */
case class Materialized(from: objects.Term) extends Origin

/** generated by lookup in partial links */
case object DefaultAssignment extends Origin
