package info.kwarc.mmt.api.utils
import info.kwarc.mmt.api._

// note graphviz does not like some characters (including -) in the tooltip attributes, which we use for classes

/** a node to be used in a [[DotGraph]] */
trait DotNode {
  def id: Path
  def label : String
  /** must be alphanumeric, space-separeated */
  def cls: String
}

/** a node to be used in a [[DotGraph]] */
trait DotEdge {
  def from: DotNode
  def to: DotNode
  def id: Option[Path]
  def label: Option[String]
  /** must be alphanumeric, space-separeated */
  def cls: String
  def weight = 1
}

/** a graph that can be converted to SVG by [[DotToSVG]] */
trait DotGraph {
   def title: String
   def nodes: Iterable[DotNode]
   def externalNodes: Option[Iterable[DotNode]]
   def edges: Iterable[DotEdge]
}

/** thrown by [[DotToSVG]] */
case class DotError(m: String) extends Exception(m)

/** converts a graph to SVG using the dot tool */
class DotToSVG(dotPath: File) {

   // note graphviz does not like some characters (including -) in the tooltip attributes
   private def dotNode(n: DotNode) = {
      s""""${n.id}" [label="${n.label}",tooltip="${n.cls}",href="${n.id.toPath}"];"""
   }

   private def dotEdge(e: DotEdge) = {
      val labelAtt = e.label match {
         case None => ""
         case Some(l) => s"""label="$l","""
      }
      val refAtt = e.id.map(p => s"""href="${p.toPath}",""").getOrElse("")
      s""""${e.from.id.toPath}" -> "${e.to.id.toPath}" [${labelAtt}${refAtt}tooltip="${e.cls}",weight=${e.weight}];"""
   }
   
   private def toDot(dg: DotGraph, f: File) {
       val file = File.Writer(f)
       def write(s: String) {file.println(s)}

       // all nodes that have been added
       var nodesDone: List[DotNode] = Nil
       // add the minimal theories

       def addNode(n: DotNode) {
          if (! nodesDone.contains(n)) {
            write(dotNode(n))
            nodesDone ::= n
          }
       }
       
       write(s"digraph ${dg.title} {")

       // add the nodes, wrapped in a cluster if there any external nodes
       if (dg.externalNodes.isDefined)
          write("subgraph cluster_local {")
       dg.nodes foreach addNode
       if (dg.externalNodes.isDefined)
          write("}")
       dg.externalNodes map {ens => ens foreach addNode}
       
       // add the edges
       dg.edges foreach {edge =>
          addNode(edge.from)
          addNode(edge.to)
          write(dotEdge(edge))
       }
         
       write("}\n")
       file.close
    }
     
    private def adaptSVG(svg: String) = {
       // we use the title attribute as a css class and remove the default style so that we can style with css
       val svgR = svg.replace("stroke=\"black\"", "").replace("<svg ", "<svg style=\"stroke:black\" ")
         .replace("xlink:title", "class")
         .replace("fill=\"black\"", "")
         .replace("xlink:href", presentation.HTMLAttributes.symref)
         .replaceAll("<!-- Generated by graphviz version.*\\s* -->", "")
       val i = svgR.indexOf("<svg")
       svgR.substring(i)
    }

    /**
     * exports in dot format
     */ 
    def apply(dg: DotGraph): String = {
      val outFile = File(System.getProperty("java.io.tmpdir")) / "graphviz.svg"
      val dotFile = outFile.setExtension("dot")
      toDot(dg, dotFile)
      val result = ShellCommand.run(dotPath.toString, "-Tsvg", "-o" + outFile, dotFile.toString)
      result foreach {m => throw DotError(m)}
      //dotFile.delete
      val svg = File.read(outFile)
      adaptSVG(svg)
    }
}